"""Domain models — pure Python dataclasses, no framework dependencies."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum


class UploadStatus(StrEnum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class JobStatus(StrEnum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class AgentRunStatus(StrEnum):
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class IngredientDetection:
    """An ingredient detected from a fridge image."""

    name: str
    normalized_name: str = ""
    confidence: float = 0.0
    bbox: dict | None = None


@dataclass
class GeneratedRecipe:
    """A recipe generated by the LLM."""

    title: str
    description: str
    ingredients: list[dict]  # [{name, amount, unit}]
    instructions: list[str]
    prep_time_minutes: int = 0
    cook_time_minutes: int = 0
    servings: int = 2
    cuisine: str = ""
    difficulty: str = "medium"


@dataclass
class ChunkResult:
    """A retrieved embedding chunk from vector search."""

    chunk_id: str
    document_id: str
    text: str
    score: float
    metadata: dict = field(default_factory=dict)


@dataclass
class RecipeReference:
    """A reference from a retrieved source used to generate a recipe."""

    source_document_id: str
    source_chunk_id: str
    relevance_score: float
    snippet: str


def new_id() -> str:
    """Generate a new UUID string."""
    return str(uuid.uuid4())


def utcnow() -> datetime:
    """Return current UTC datetime."""
    return datetime.utcnow()
